services:

  postgres:
    image: postgres:18.1
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro  # опционально init sql
    networks:
      - gallery-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    env_file: 
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - gallery-net

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        SERVER_NAME: ${SERVER_NAME:-localhost}
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - backend
    networks:
      - gallery-net

volumes:
  pgdata:

networks:
  gallery-net:
    driver: bridge
