CREATE SCHEMA IF NOT EXISTS public;
CREATE TABLE IF NOT EXISTS public.users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL UNIQUE,
  email text[] NOT NULL,
  telegramID text,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  is_active boolean DEFAULT true,
  role text DEFAULT 'user'
);

CREATE TABLE IF NOT EXISTS telegram_auth_used (
  tg_id TEXT,
  auth_date BIGINT,
  PRIMARY KEY(tg_id, auth_date)
);

CREATE TABLE IF NOT EXISTS public.cards (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  path text NOT NULL UNIQUE,
  year integer NOT NULL CHECK (year >= 0 AND year <= 9999),
  title text NOT NULL,
  image_count integer NOT NULL DEFAULT 0 CHECK (image_count >= 0),
  sort_order integer NOT NULL DEFAULT 0,
  preview_key text,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT cards_path_format CHECK (path ~ '^[0-9]{1,4}/[A-Za-z]+$')
);

CREATE INDEX IF NOT EXISTS idx_cards_sort_order
ON public.cards (sort_order ASC, id ASC);

CREATE INDEX IF NOT EXISTS idx_cards_year
ON public.cards (year DESC);
