CREATE SCHEMA IF NOT EXISTS public;
CREATE TABLE IF NOT EXISTS public.users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL UNIQUE,
  email text[] NOT NULL,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  is_active boolean DEFAULT true,
  role text DEFAULT 'user',
  phone text
);
