CREATE SCHEMA IF NOT EXISTS public;
CREATE TABLE IF NOT EXISTS public.users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL UNIQUE,
  email text[] NOT NULL,
  telegramID text,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  is_active boolean DEFAULT true,
  role text DEFAULT 'user'
);

CREATE TABLE IF NOT EXISTS telegram_auth_used (
  tg_id TEXT,
  auth_date BIGINT,
  PRIMARY KEY(tg_id, auth_date)
);