server {
        listen 80 default_server;
        listen [::]:80 default_server;

        include       /etc/nginx/conf.d/*.conf;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;

        root /var/www/dist;

        index index.html;

        server_name EXAMPLE.COM;

        location /api/ {
                proxy_pass http://localhost:3000;
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
                try_files $uri $uri/ /index.html;
        }

        # Ограничение от дудоса - не больше 5 запросов в секунду с IP
        limit_req_zone $binary_remote_addr zone=req_limit_per_ip:10m rate=5r/s;

        # Безопасность
        add_header X-Frame-Options "DENY" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Referrer-Policy "no-referrer-when-downgrade" always;
        add_header Content-Security-Policy "default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self' 'unsafe-inline';" always;

        # HTTPS на проде нужен для HSTS
        # add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;

        gzip on;
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 5;
        gzip_buffers 16 8k;
        gzip_http_version 1.1;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}